name: Trigger auto deployment for node-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node-api-AutoDeployTrigger-92f7a9d9-ddb9-4245-8f16-bfe576bf9e6b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NODEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NODEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NODEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: nodeapi.azurecr.io
          registryUsername: ${{ secrets.NODEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NODEAPI_REGISTRY_PASSWORD }}
          containerAppName: node-api
          resourceGroup: node-api
          imageToBuild: nodeapi.azurecr.io/node-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


